wknetic:
  jwt:
    secret: "WkNeticCoreSecretKeyForSpringSecurityVersion2026MakeItLong"
    expiration: 2592000
spring:
  data:
    redis:
      # 基础连接信息
      host: localhost       # 如果是用 Docker 部署，这里可能需要改成 'redis' 或者服务器 IP
      port: 6379
      password: 123456      # 如果没有密码留空，如果有必须填
      database: 0           # Redis 默认有 16 个库 (0-15)，我们用 0 号库
      # 连接超时时间
      timeout: 3000ms
      # Lettuce 连接池配置 (高并发关键)
      lettuce:
        pool:
          max-active: 8     # 最大连接数 (默认 8)，生产环境可根据并发量调大
          max-wait: -1ms    # 最大阻塞等待时间 (-1 表示无限等待)
          max-idle: 8       # 最大空闲连接
          min-idle: 0
  datasource:
    # 1. 数据库驱动 (MySQL 8+ 推荐用 cj.jdbc.Driver)
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 2. 连接地址 (关键参数详解见下方)
    # ⚠️ 请确保先手动创建数据库: CREATE DATABASE wknetic DEFAULT CHARACTER SET utf8mb4;
    url: jdbc:mysql://127.0.0.1:3306/cn.wekyjay.wknetic.test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    # 3. 账号密码
    username: root
    password: 1251840505
    # 4. 连接池配置 (HikariCP - SpringBoot默认最强连接池)
    hikari:
      minimum-idle: 5        # 最小空闲连接
      maximum-pool-size: 20  # 最大连接数
      max-lifetime: 1800000  # 连接最大存活时间(ms)
      connection-timeout: 30000 # 等待连接超时时间(ms)